---

- name: Install Git
  package:
    name: git
    state: latest

- name: Install ViM
  package:
    name: vim
    state: latest

- name: Install nano
  package:
    name: nano
    state: latest
  
- name: Install net-tools
  package:
    name: net-tools
    state: latest

- name: Install telnet
  package:
    name: telnet
    state: latest

- name: Install wget
  package:
    name: wget
    state: latest

- name: Install curl
  package:
    name: curl
    state: latest
  